name: CAL-BLOG Infrastructure CI/CD

on:
  push:
    branches:
      - calblog-infra

jobs:
  set-directory:
    name: Set Directory
    runs-on: ubuntu-latest

    steps:
      - name: Checkout calblog-cicd branch into a separate directory
        uses: actions/checkout@v3
        with:
          ref: calblog-cicd
          path: calblog-cicd
      
      - name: Checkout calblog-infra branch into a separate directory
        uses: actions/checkout@v3
        with:
          ref: calblog-infra
          path: calblog-infra

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      # - name: Set github repository from secret to github action environment variable
      #   working-directory: master/1.WORKFLOWS_SCRIPT
      #   env:
      #     GIT_PROFILE_CSV_DATA: ${{ secrets.CAL_SC_GIT_REPO_PROFILE_ENCODED }}cd 
      #     GIT_MASTER_USER_NAME: ${{ env.GIT_MASTER_USER_NAME }}
      #     GIT_REPO_NAME: ${{ env.GIT_REPO_NAME }}
      #     GH_TOKEN: ${{ secrets.CAL_SC_GIT_MASTER_USER_TOKEN }}
      #   run: |
      #     echo "$GIT_PROFILE_CSV_DATA" | base64 --decode > git_repo_profile.csv
      #     bash set_git_auth_url_with_csv_data_to_gh_repo_secret.sh

      # - name: Set cloudflare email and apikey from secret to github action environment variable
      #   working-directory: master/1.INFRA/3.WORKFLOWS_SCRIPT
      #   env:
      #     CLOUDFLARE_CSV_DATA: ${{ secrets.CAL_SC_CLOUDFLARE_ENCODED }}
      #     GIT_MASTER_USER_NAME: ${{ env.CAL_SC_OPS_USER_NAME }}
      #     GIT_REPO: "CAL-INFRA"
      #     GH_TOKEN: ${{ secrets.CAL_SC_INFRA_GIT_REPO_MASTER_TOKEN }}
      #   run: |
      #     echo "$CLOUDFLARE_CSV_DATA" | base64 --decode > cloudflare_profile.csv
      #     bash set_cloudflare_profile_with_csv_data_to_gh_repo_secret.sh
